### ISSUE TITLE
[Feature Request] Play All

### ISSUE THREAD

**Issue by elightcap** [marios8543/Jellyfin-CLI#7]
I just found this project, maybe its abandonded, but im into it.

Looking into a way to play entire albums/libraries without having to click each song individually

**Comment by marios8543** [comment]
Well I wouldn't call it abandoned, I don't really actively use it anymore and at the same time it has most of the features I want so I don't add new stuff but I try to fix bugs to the best of my ability.

I thought it played albums without clicking next ? Maybe I'm remembering wrong. Music was never really the focus of this project anyway. Maybe [this](https://github.com/tryffel/jellycli) is closer to what you're looking for ?
